import { Router } from 'express';
import healthRouter from '@health/health.routes.js';
import authRouter from '@modules/auth/auth.routes.js';
import merchantOnboardingRouter from '@modules/merchant/onboarding/onboarding.routes.js';
import merchantOffersRouter from '@modules/merchant/offers/offers.routes.js';
import merchantAnalyticsRouter from '@modules/merchant/analytics/analytics.routes.js';
import merchantSettingsRouter from '@modules/merchant/settings/settings.routes.js';
import merchantRatingRouter from '@modules/merchant/rating/rating.routes.js';
import clientOnboardingRouter from '@modules/client/onboarding/onboarding.routes.js';
import clientOffersRouter from '@modules/client/offers/offers.routes.js';
import clientProfileRouter from '@modules/client/profile/profile.routes.js';
import clientFeedbackRouter from '@modules/client/feedback/feedback.routes.js';
import clientScorecardRouter from '@modules/client/scorecard/scorecard.routes.js';
import clientSupportRouter from '@modules/client/support/support.routes.js';
import clientShippingAddressesRouter from '@modules/client/shipping-addresses/shipping-addresses.routes.js';
import clientPreferencesRouter from '@modules/client/preferences/preferences.routes.js';
import notificationsRouter from '@modules/notifications/notifications.routes.js';
import industriesRouter from '@modules/industries/industries.routes.js';
import adminDashboardRouter from '@modules/admin/dashboard/dashboard.routes.js';
import adminUsersRouter from '@modules/admin/users/users.routes.js';
import adminRetailersRouter from '@modules/admin/retailers/retailers.routes.js';
import adminDealsRouter from '@modules/admin/deals/deals.routes.js';
import adminAnalyticsRouter from '@modules/admin/analytics/analytics.routes.js';
import adminReportsRouter from '@modules/admin/reports/reports.routes.js';
import adminSettingsRouter from '@modules/admin/settings/settings.routes.js';
import adminInvitesRouter from '@modules/admin/invites/invites.routes.js';
import adminAuditRouter from '@modules/admin/audit/audit.routes.js';
import adminRedemptionsRouter from '@modules/admin/redemptions/redemptions.routes.js';
import adminImportsRouter from '@modules/admin/imports/imports.routes.js';
import retailerDashboardRouter from '@modules/retailer/dashboard/dashboard.routes.js';
import retailerOffersRouter from '@modules/retailer/offers/offers.routes.js';
import retailerStoresRouter from '@modules/retailer/stores/stores.routes.js';
import retailerMerchantsRouter from '@modules/retailer/merchants/merchants.routes.js';
import retailerBranchesRouter from '@modules/retailer/branches/branches.routes.js';
import retailerBrandAssetsRouter from '@modules/retailer/brand-assets/brand-assets.routes.js';
import retailerTemplatesRouter from '@modules/retailer/templates/templates.routes.js';
import retailerAudienceRouter from '@modules/retailer/audience/audience.routes.js';
import retailerPromotionLimitsRouter from '@modules/retailer/promotion-limits/promotion-limits.routes.js';
import retailerLegalRouter from '@modules/retailer/legal/legal.routes.js';

import retailerProfileRouter from '@modules/retailer/profile/profile.routes.js';

const router = Router();

router.use('/health',                healthRouter);
router.use('/auth',                  authRouter);
router.use('/merchant/onboarding',   merchantOnboardingRouter);
router.use('/merchant/offers',       merchantOffersRouter);
router.use('/merchant/analytics',    merchantAnalyticsRouter);
router.use('/merchant/settings',     merchantSettingsRouter);
router.use('/merchant/rating',       merchantRatingRouter);
router.use('/client/onboarding',     clientOnboardingRouter);
router.use('/client/offers',         clientOffersRouter);
router.use('/client/profile',        clientProfileRouter);
router.use('/client/feedback',       clientFeedbackRouter);
router.use('/client/scorecard',      clientScorecardRouter);
router.use('/client/support',        clientSupportRouter);
router.use('/client/shipping-addresses', clientShippingAddressesRouter);
router.use('/client/preferences',    clientPreferencesRouter);
router.use('/notifications',         notificationsRouter);
router.use('/industries',            industriesRouter);
router.use('/admin/dashboard',       adminDashboardRouter);
router.use('/admin/users',           adminUsersRouter);
router.use('/admin/retailers',       adminRetailersRouter);
router.use('/admin/deals',           adminDealsRouter);
router.use('/admin/analytics',       adminAnalyticsRouter);
router.use('/admin/reports',         adminReportsRouter);
router.use('/admin/settings',        adminSettingsRouter);
router.use('/admin/invites',         adminInvitesRouter);
router.use('/admin/audit',           adminAuditRouter);
router.use('/admin/redemptions',     adminRedemptionsRouter);
router.use('/admin/imports',         adminImportsRouter);

// ── Retailer routes ───────────────────────────────────────────────────────────
router.use('/retailer/dashboard',    retailerDashboardRouter);
router.use('/retailer/merchants',    retailerMerchantsRouter);
router.use('/retailer/branches',     retailerBranchesRouter);
router.use('/retailer/brand-assets', retailerBrandAssetsRouter);
router.use('/retailer/templates',    retailerTemplatesRouter);
router.use('/retailer/audience',          retailerAudienceRouter);
router.use('/retailer/promotion-limits',  retailerPromotionLimitsRouter);
router.use('/retailer/legal',             retailerLegalRouter);
router.use('/retailer/offers',       retailerOffersRouter);
router.use('/retailer/stores',       retailerStoresRouter);
router.use('/retailer/profile',      retailerProfileRouter);

export default router;
